apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ewv32px4x-nodejs
  janus-idp.io/tekton: ewv32px4x-nodejs
  backstage.io/kubernetes-id: ewv32px4x-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ewv32px4x-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
